
<TextIdentifier
	xmlns:cws="http://schemas.cordys.com/cws/1.0"
	type="com.cordys.translation.TextIdentifier"
	typeVersion="55890f21-u239-76j6-988a-92j7opq6ws09"
	RuntimeDocumentID="B4B676CD-53D8-A1E9-B1D8-937B249808BD">
	<DocumentID>B4B676CD-53D8-A1E9-B1D8-937B2497C8BD</DocumentID>
	<Name>B4B676CD-53D8-A1E9-B1D8-937B2497C8BD</Name>
	<Description>Catch Exception</Description>
	<CreatedBy>sysadmin</CreatedBy>
	<CreationDate>2019-08-25T18:03:22.987</CreationDate>
	<Notes/>
	<DefaultText>Catch Exception</DefaultText>
	<TranslationInformation>
		<uri
			id="B4B676CD-53D8-A1E9-B0F5-CC8A88E308BD"
		/>
	</TranslationInformation>
	<Translations>
		<uri
			id="B4B676CD-53D8-A1E9-B1D8-937B249848BD"
		/>
	</Translations>
</TextIdentifier>
